### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by MacBone** [DanaePlays/mlox-rules#13]
**1. Better Robes and Robert's Bodies**

Is Better Robes.ESP compatible with Robert's Bodies? I'm still getting an error that Better Bodies is needed.

https://www.reddit.com/r/Morrowind/comments/mz27h4/using_better_robes_with_roberts_bodies_in/
https://www.reddit.com/r/Morrowind/comments/pfn167/how_to_fix_armor_clipping_with_roberts_bodies/

The mod description says there is some conflict between [Robert's Bodies](https://www.nexusmods.com/morrowind/mods/43138) and some skimpier clothing mods, but I'm not sure how incompatible they are.

Mods that are not recognizing Robert's Bodies:

Better Robes.ESP
The Shrine of Mephala by Westlyn

**2. Tamriel Data**

Some mods are looking for the old TR_Data.esm rather than the newer Tamriel_Data.esm:

- Better Robes TR 
- Better Robes TR_Patch.esp 

**3. Non-Pointy Mountainous Red Mountain**

Some mods are looking for MRM.esm and are not recognizing MRM-Non Pointy.esm.

From Darknut's Greater Dwemer Ruins:

DN-GDRv1.2.MRMnp.esp

[MRM_PuzzleCanal_Fix.esp](https://mw.modhistory.com/download--15169)

[This Reddit thread](https://www.reddit.com/r/Morrowind/comments/3vh4jh/do_somebody_have_mrmnon_spiky_mrm_dngdr_patch_and/) recommends that the Puzzle Canal Fix be used with MRM NP.

**4. Vanilla Friendly Wearables**

Vanilla friendly wearables expansion.esm
Vanilla friendly weareables expansion.esp

From [RandomPal's Random Mods and Patches](https://www.nexusmods.com/morrowind/mods/48683?tab=files). Older versions of Wearables were spelled Weareables. There should be only one version of Vanilla Friendly Wearables installed.

**Comment by DanaePlays** [comment]
Better Bodies requirements have been removed from the base rules
