### ISSUE TITLE
Improving BalmoraDocks.esp Conflict Check

### ISSUE THREAD

**Issue by Toriansel** [DanaePlays/mlox-rules#150]
https://github.com/DanaePlays/mlox-rules/blob/a4a071419f377b48432191c24cac1fb1a02be7f7/mlox_user.txt#L1182

If the above line is changed to the following the conflict isn't displayed if the updated version of the esp is installed.

[SIZE !185150 BalmoraDocks.esp]

**Comment by MasssiveJuice08** [comment]
Closed by 2577de6
