### ISSUE TITLE
BalmoraDocks.esp order with respect to BCoM_WaterWorks.ESP

### ISSUE THREAD

**Issue by Toriansel** [DanaePlays/mlox-rules#151]
https://github.com/DanaePlays/mlox-rules/blob/a4a071419f377b48432191c24cac1fb1a02be7f7/mlox_user.txt#L1061

In addition to being below the "Beautiful cities of Morrowind.esp", BalmoraDocks.esp needs to be below BCoM_WaterWorks.ESP for conflicts to work out correctly.

**Comment by MasssiveJuice08** [comment]
I'll take a look at this for you and check the plugins to make sure things are loaded correctly.
