### ISSUE TITLE
Multiple cycle detected warnings when run mlox v1.0.3 with updated rules

### ISSUE THREAD

**Issue by karmacat77** [DanaePlays/mlox-rules#6]
Hi. When I run mlox.exe v1.0.3 by itself it works fine, but when I try to use the updated rules it throws multiple (around 60) 'cycle detected' warnings similar to this one:

WARNING (mlox.pluggraph): C:\Users\XXXX\AppData\Local\mlox\mlox\mlox_base.txt:1004: Cycle detected, not adding: "lgnpc_teluvirith.esp" -> "lgnpc_secretmasters_v1_30.esp".  

If you don't experience the same error, I can provide my log.  Thanks.

**Comment by DanaePlays** [comment]
Just got back home and to my PC, I'll update mu mlox and see what it says with the latest rules. Thanks for the heads up!

**Comment by DanaePlays** [comment]
Not seeing the warning on my install, do you still have it after checking you have all the latest (mlox+rules) ?

**Comment by karmacat77** [comment]
Hi Danae.  Yes, it's still giving me cycle errors.  All program and base/user files are the latest.  Fyi, I've attached the error log, pre/post loadorder, and morrowind.ini.  (Fyi, abot's 'mlox_user.txt' from 29-Jun-21 also gives me some cycle errors, but not as many).  Thanks
[mlox cycle error log.txt](https://github.com/DanaePlays/mlox-rules/files/7161110/mlox.cycle.error.log.txt)
[current_loadorder.txt](https://github.com/DanaePlays/mlox-rules/files/7161115/current_loadorder.txt)
[mlox_new_loadorder.txt](https://github.com/DanaePlays/mlox-rules/files/7161116/mlox_new_loadorder.txt)
[Morrowind.ini.txt](https://github.com/DanaePlays/mlox-rules/files/7161123/Morrowind.ini.txt)

**Comment by DanaePlays** [comment]
Those should be fixed now
